---
sidebar: sidebar
permalink: install-setup/set-up-data-access.html
keywords: 
summary:  
---
= Enable data access from SAN hosts to your ASA r2 storage system
:icons: font
:imagesdir: ../media/

[.lead]

To set up data access, you should ensure that the critical parameters and settings on your SAN client for proper operation with ONTAP are configured correctly.  If you are providing storage for your VMware environment, you should install OTV 10.3 to simply the management of your ASA r2 storage.

== Set up data access from SAN hosts

The configuration necessary to set up data access to your ASA r2 system from your SAN hosts varies depending on the host operating system and the protocol. Correct configuration is important for best performance and successful failover.  

See the ONTAP SAN host documentation for link:https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_8.html[VMware vSphere SCSI clients^], link:https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html[VMware vSphere NVMe clients^] and link:https://docs.netapp.com/us-en/ontap-sanhost/overview.html[other SAN clients^] to properly configure your hosts to connect to your ASA r2 system.

== Migrate VMware virtual machines

If you need to migrate your VM workload from an ASA storage system to an ASA r2 storage system, NetApp recommends that you use link:https://www.vmware.com/products/cloud-infrastructure/vsphere/vmotion[VMware vSphere vMotion^] to perform a live, non-disruptive migration of your data.

== Migrate data from a third-party storage system

Beginning with ONTAP 9.17.1, you can use Foreign LUN Import (FLI) to migrate data from a LUN on a third-party storage system to an ASA r2 system. 

FLI supports both online and offline migrations. In an online migration, the client system stays online while data is copied from the third-party storage system to the ONTAP storage system. Online migrations are supported by Windows, Linux, and ESXi host operating systems.  In an offline migration, the client system is taken offline, the LUN data is copied from the third-party storage system to the ONTAP storage system; then the client system is brought back online.

.Related information

* Learn how to perform an link:https://docs.netapp.com/us-en/ontap-fli/san-migration//concept_fli_offline_workflow.html[FLI offline migration^].
* Learn how to perform an link:https://docs.netapp.com/us-en/ontap-fli/san-migration//concept_fli_online_workflow.html[FLI online migrations^].

== Configure your ASA r2 system as a storage provider in your VMware environment

You can use ONTAP tools for VMware to easily enable your ASA r2 system as a storage provider in your VMware environment.

ONTAP tools for VMware vSphere is a set of tools that work in conjunction with VMware vCenter Server Virtual Appliance (vCSA) for easy management of virtual machines on your VMware ESXi hosts. 

ASA r2 systems are supported by link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/concepts/ontap-tools-overview.html[ONTAP tools for VMware vSphere 10.3^] and later. 

Learn how to link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/ontap-tools-deployment.html[Deploy ONTAP tools for VMware^] and then use it to do the following: 

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-vcenter.html[Add vCenter Server instances^]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/configure-esx-server-multipath-and-timeout-settings.html[Configure your ESXi host settings^]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/discover-storage-systems-and-hosts.html[Discover your ASA r2 storage system and hosts^]


.What's next?

You are ready to link:../manage-data/provision-san-storage.html[provision storage] to enable your SAN hosts to read and write data to storage units.

// 2025 July 24, ONTAPDOC-2696
// 2024 Sept 23, ONTAPDOC 1925