---
sidebar: sidebar
permalink: install-setup/set-up-data-access.html
keywords: 
summary:  
---
= Set up data access from your SAN host to your ASA r2
:icons: font
:imagesdir: ../media/

[.lead]

To set up data access to your SAN clients, you should ensure that specific parameters and settings on the client that are critical for proper operation with ONTAP are configured correctly. The necessary configuration varies depending on the host operating system and the protocol. Correct configuration is important for best performance and successful failover.  

See ONTAP SAN host documentation for link:https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_8.html[VMware vSphere SCSI clients^], link:https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html[VMware vSphere NVMe clients^] and link:https://docs.netapp.com/us-en/ontap-sanhost/overview.html[other SAN clients^] to properly configure your hosts to connect to your ASA r2.

== Non-disruptive data migration

If you need to migrate your VM workload from an ASA storage system to an ASA r2 storage system, NetApp recommends that you use vSphere vMotion to perform a live, non-disruptively migration of your data.

.What's next?

You are ready to link:../manage-data/provision-san-storage.html[provision storage] to enable your SAN hosts to read and write data to storage units.