---
sidebar: sidebar
permalink: install-setup/set-up-data-access.html
keywords: 
summary:  
---
= Set up data access
:icons: font
:imagesdir: ../media/

[.lead]

To set up data access to your SAN clients, you should ensure that specific parameters and settings on the client that are critical for proper operation with ONTAP are configured correctly. The necessary configuration varies depending on the host operating system and the protocol. Correct configuration is important for best performance and successful failover.  

.Steps

. See link:https://docs.netapp.com/us-en/ontap-sanhost/overview.html[ONTAP SAN host documentation] to properly configure your hosts to connect to your ASA r2.
. Optionally, if you are configuring a VMware hosts, use vSphere vMotion to migrate your VM workload.
+
If you need to migrate your VM workload from an ASA storage system to an ASA r2 storage system, NetApp recommends that you use vSphere vMotion to perform a live, non-disruptively migration of your data. 