---
sidebar: sidebar
permalink: secure-data/migrate-encryption-keys-between-key-managers.html
keywords: onboard key manager, external key manager, configure, migrate keys, store keys, authentication keys, encryption keys, asa r2
summary: "You can use the ONTAP onboard key manager on your ASA r2 system or an external key manager or both (in one case) to manage data encryption keys."
---
= Migrate ONTAP data encryption keys between key managers on your ASA r2 system
:icons: font
:imagesdir: ../media/

[.lead]
You can manage your data encryption keys using either the ONTAP onboard key manager on your ASA r2 system or an external key manager (or both). External key managers can only be enabled at the storage VM level. At the ONTAP cluster level, you can enable either the onboard key manager or an external key manager.  

[cols="2,2" options="header"]
|===
// header row
| If you enable your key manager at the...
| You can use...


// first body row
| Cluster level only
a| Either the onboard key manager or an external key manager

| Storage VM level only
| An external key manager only

a| Both the cluster and storage VM level
a| 
One of the following key manager combinations:

* Option 1
+
Cluster level: Onboard key manager
+
Storage VM level: External key manager

* Option 2
+
Cluster level: External key manager 
+
Storage VM level: External key manager

// table end
|===

== Migrate keys between key managers at the ONTAP cluster level

Beginning with ONTAP 9.16.1 you can use the ONTAP command line interface (CLI) to migrate keys between key managers at the cluster level. 

// start tabbed area

[role="tabbed-block"]
====

.From onboard to external 
--
.Steps

. Set the privilege level to advanced:
+
[source, cli]
----
set -privilege advanced
----

. Create an inactive external key manager configuration:  
+
[source, cli]
----
security key-manager external create-config 
----

. Switch to the external key manager:
+
[source, cli]
----
security key-manager keystore enable -vserver <storage_vm_name> -type KMIP
----

. Delete the onboard key manager configuration:
+
[source, cli]
----
security key-manager keystore delete-config -vserver <storage_vm_name> -type OKM
----

. Set the privilege level to admin:
+
[source, cli]
----
set -privilege admin
----
--

.From external to onboard
--

.Steps

. Set the privilege level to advanced:
+
[source, cli]
----
set -privilege advanced
----

. Create an inactive onboard key manager configuration: 
+
[source, cli]
----
security key-manager onboard create-config
----

. Enable the onboard key manager configuration: 
+
[source, cli]
----
security key-manager keystore enable -vserver <storage_vm_name> -type OKM
----

. Delete the external key manger configuration
+
[source, cli]
----
security key-manager keystore delete-config -vserver <storage_vm_name> -type KMIP
----

. Set the privilege level to admin:
+
[source, cli]
----
set -privilege admin
----

--

====

// end tabbed area


== Migrate keys between key managers across ONTAP cluster and storage VM levels

You can use the ONTAP command line interface (CLI) to migrate keys between the key manager at the cluster level and a key manager at the storage VM level.  


.Steps

. Set the privilege level to advanced:
+
[source, cli]
----
set -privilege advanced
----

. Migrate the keys:
+
[source, cli]
----
security key-manager key migrate -from-vserver <storage_vm_name> -to-vserver <storage_vm_name>
----

. Set the privilege level to admin:
+
[source, cli]
----
set -privilege admin
----

// 2025 Feb 20, ONTAPDOC-2798
// 2025 Jan 22, ONTAPDOC-1070
// 2024 Nov 07, ONTAPDOC 2491