settings:
  name: ASA r2
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true

sidebar: 
  entries:
  - title: ASA r2 docs
    url: /index.html
  - section: get-started
  - section: install-setup
  - section: manage-data 
  - section: data-protection
  - section: secure-data
  - section: administer
  - section: monitor
  - section: learn-more
  - section: get-help
  - title: Legal notices
    url: /legal-notices.html

product-family:
  name: ONTAP  
  repo: ontap-family
