---
sidebar: sidebar
permalink: learn-more/additional-supported-ontap-features.html
keywords: asa r2, asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30, cli, command line interface, clustered external key servers, external key management, encryption at rest, administrator access management, client authentication, oauth 2.0, saml authentication, fips compliance, link aggregation groups, iscsi, fibre channel, fc, nvme, nvme unmap, hole punch, deallocation, system manager 
summary: "Because ASA r2 systems run a streamlined version of ONTAP, many common ONTAP tasks and System Manager functions are performed the same way on ASA r2 systems as on other ONTAP systems."
---
= Common ONTAP features supported on ASA r2 systems
:icons: font
:imagesdir: ../media/

[.lead]

Because ASA r2 systems run a streamlined version of ONTAP, many common ONTAP tasks and System Manager functions are performed the same way on ASA r2 systems as on other ONTAP systems.

For more information about common features and functions, see the following ONTAP documentation.

== Data protection

Learn more about common data protection features supported on ASA r2 systems.

=== Clustered external key servers
You can configure connectivity to clustered external key management servers on a storage VM. With clustered key servers, you can designate primary and secondary key servers on a storage VM. When registering keys, ONTAP will first attempt to access a primary key server before sequentially attempting to access secondary servers until the operation completes successfully, preventing duplication of keys.

link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-cluster-key-server-task.html[Learn to configure clustered external key servers^].

=== External key management for encryption at rest
You can use one or more KMIP servers to secure the keys the cluster uses to access encrypted data.

* link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/enable-external-key-management-96-later-hw-task.html[Enable external key management^].
* link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/enable-external-key-management-96-later-nve-task.html[Enable external key management (NVE)^].

== Data security

Learn more about common data security features supported on ASA r2 systems.

=== Administrator access management
The role assigned to an administrator determines which functions the administrator can perform. Predefined roles for cluster administrators and storage VM administrators are provided by System Manager. You assign the role when you create the administrator’s account, or you can assign a different role later.

* link:https://docs.netapp.com/us-en/ontap/task_security_administrator_access.html[Learn to manage administrator access with System Manager^].

=== Client authentication and authorization

ONTAP uses standard methods to secure client and administrator access to storage and to protect against viruses. Advanced technologies are available for encryption of data at rest and for WORM storage. ONTAP authenticates a client machine and user by verifying their identities with a trusted source. ONTAP authorizes a user to access a file or directory by comparing the user's credentials with the permissions configured on the file or directory.

link:https://docs.netapp.com/us-en/ontap/concepts/client-access-storage-concept.html[Learn about client authentication and authorization^].

=== OAuth 2.0 authentication
You can use the Open Authorization (OAuth 2.0) framework to control access to your ONTAP clusters. OAuth 2.0 restricts and controls access to protected resources using signed access tokens. 

link:https://docs.netapp.com/us-en/ontap/authentication/overview-oauth2.html[Learn about OAuth 2.0 authentication^].

=== SAML authentication and administrator access

You can configure and enable Security Assertion Markup Language (SAML) authentication for web services.  SAML authenticates users by an external Identity Provider (IdP) instead of the directory service providers such as Active Directory and LDAP. 

link:https://docs.netapp.com/us-en/ontap/system-admin/configure-saml-authentication-task.html[Learn to Configure SAML authentication^].


== Networking

Learn more about common networking features supported on ASA r2 systems.

=== FIPS compliance 
ONTAP is compliant in the Federal Information Processing Standards (FIPS) 140-2 for all SSL connections. You can turn SSL FIPS mode on and off, set SSL protocols globally, and turn off any weak ciphers such as RC4 within ONTAP.

Beginning with ONTAP 9.18.1 postquantum computing cryptographic algorithms are supported for SSL. These algorithms provide additional protection against potential future quantum computing attacks, and are available when SSL FIPS mode is disabled.

* link:https://docs.netapp.com/us-en/ontap/networking/configure_network_security_using_federal_information_processing_standards_fips.html[Learn to configure FIPS for all SSL connections^]. 

=== Link Aggregation Groups (LAGs)

An interface group, also known as a Link Aggregation Group (LAG), is created by combining two or more physical ports on the same node into a single logical port. The logical port provides increased resiliency, increased availability, and load sharing.

link:https://docs.netapp.com/us-en/ontap/networking/combine_physical_ports_to_create_interface_groups.html[Learn about Link Aggregation Groups^].

== SAN Protocols
ASA r2 systems support all SAN protocols (iSCSI, FC, NVMe/FC, NVMe/TCP). 

* link:https://docs.netapp.com/us-en/ontap/san-admin/san-host-provisioning-concept.html[Learn more about the iSCSI protocol^].
* link:https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html[Learn more about the Fibre Channel (FC) protocol^].
* link:https://docs.netapp.com/us-en/ontap/concept_nvme_provision_overview.html[Learn about the NVMe protocol ^].
** link:https://docs.netapp.com/us-en/ontap/san-admin/nvme-copy-offload.html[Learn to configure NVMe copy offload^].
+
Beginning with ONTAP 9.18.1, NVMe copy offload is supported. NVMe copy offload enables an NVMe host to offload copy operations from its CPU to the CPU of the ONTAP storage controller.  The host can copy data from one NVMe namespace to another while reserving its CPU resources for application workloads.

** link:https://docs.netapp.com/us-en/ontap/san-admin/enable-space-allocation.html[Learn more about space allocation (unmap) for NVMe^].
+
Beginning with ONTAP 9.16.1, space deallocation (also called “hole punching” and “unmap”) is enabled for NVMe namespaces by default. Space deallocation allows a host to deallocate unused blocks from namespaces to reclaim space.

== System Manager

You can search for various actions, objects,and information topics in System Manager. You can also search table data for specific entries.

link:https://docs.netapp.com/us-en/ontap/task_admin_search_filter_sort.html[Learn to search, filter and sort information in System Manager^].
