---
sidebar: sidebar
permalink: learn-more/cli-support.html
keywords: asa r2, asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c80 asa c60, asa c30, cli
summary: "Certain ONTAP commands are  not supported on ASA r2 systems (ASA A1K, ASA 70, ASA 90)."
---
= ONTAP CLI support for ASA r2 storage systems
:icons: font
:imagesdir: ../media/

[.lead]

Instead of traditional aggregates, which own a specific set of the disks available in a storage system, ASA r2 systems use a _storage availability zone_.  A storage availability zone is a common pool of storage that has access to all available disks in the storage system.  The storage availability zone is visible to both nodes in an ASA r2 HA pair.   When a storage unit (LUN or NVMe namespace) is created, ONTAP automatically creates a volume containing a storage virtual machine (VM) in the storage availability zone to house the storage unit.

Because of this simplified approach to storage management, `storage aggregate` commands are not supported on ASA r2 systems.  Support for certain `lun` and `volume` commands and parameters is also limited.  

The following commands and command sets are not supported on ASA on r2:

// Start snippet: collapsible block (open on page load)
.Unsupported `lun` commands
[%collapsible%closed]
====
* `lun copy`
* `lun geometry`
* `lun import`
* `lun mapping add-reportng-nodes`
* `lun mapping-remove-reporting-nodes`
* `lun maxsize`
* `lun move`
* `lun move-in-volume`
+
This command is replaced with lun rename/vserver nvme namespace rename.
* `lun transition`

====
// End snippet

// Start snippet: collapsible block (open on page load)
.Unsupported `volume` commands and parameters
[%collapsible%closed]
====
* `volume autosize`
* `volume create`
* `volume delete`
* `volume expand`
* `volume modify`
+
This command is not available when used in conjunction with the following parameters: 
+
** `-anti-ransomware-state`
** `-autosize`
** `-autosize-mode`
** `-autosize-shrik-threshold-percent`
** `-autosize-reset`
** `-group`
** `-is-cloud-write-enabled`
** `-is-space-enforcement-logical`
** `-max-autosize`
** `-min-autosize`
** `-offline`
** `-online`
** `-percent-snapshot-space`
** `-qos*`
** `-size`
** `-snapshot-policy`
** `-space-guarantee`
** `-space-mgmt-try-first`
** `-state`
** `-tiering-policy`
** `-tiering-minimum-cooling-days`
** `-user`
** `-unix-permisions`
** `-vserver-dr-protection`
* `volume make-vsroot`
* `volume mount`
* `volume move`
* `volume offline`
* `volume rehost`
* `volume rename`
* `volume restrict`
* `volume transition-prepare-to-downgrade`
* `volume unmount`

====
// End snippet

// Start snippet: collapsible block (open on page load)
.Unsupported `volume clone` commands
[%collapsible%closed]
====

* `volume clone create`
* `volume clone split`

====
// End snippet

// Start snippet: collapsible block (open on page load)
.Unsupported `volume snaplock` commands
[%collapsible%closed]
====

* `volume snaplock modify`

====
// End snippet


// Start snippet: collapsible block (open on page load)
.Unsupported `volume snapshot` commands
[%collapsible%closed]
====

* `volume snapshot`
* `volume snapshot autodelete modify`
* `volume snapshot policy modify`
====
// End snippet

// Start snippet: collapsible block (open on page load)
.Unsupported `volume` command sets
[%collapsible%closed]
====

* `volume activity-tracking`
* `volume analytics`
* `volume conversion`
* `volume file`
* `volume flexcache`
* `volume flexgroup`
* `volume inode-upgrade`
* `volume object-store`
* `volume qtree`
* `volume quota`
* `volume reallocation`
* `volume rebalance`
* `volume recovery-queue`
* `volume schedule-style`

====
// End snippet

// Start snippet: collapsible block (open on page load)
.Unsupported `storage` commands
[%collapsible%closed]
====

* `storage failover show-takeover`
* `storage failover show-giveback`
* `storage aggregate relocation`
* `storage disk assign`
* `storage disk partition`
* `storage disk reassign`
====
// End snippet

.For more information

See the link:https://docs.netapp.com/us-en/ontap-cli/[ONTAP command reference] for a full list of supported commands

== Set up an ONTAP ASA r2 cluster using the CLI

It is recommended that you link:../install-setup/initialize-ontap-cluster.html[use System Manager to set up your ONTAP ASA r2 cluster]. System Manager offers a quick and easy guided workflow to get your cluster up and running. However, if you are accustomed to working with ONTAP commands, the ONTAP command line interface (CLI) can optionally be used for cluster setup.  Cluster set up using the CLI offers no additional options or advantages than cluster set up using System Manager.  

During cluster setup, your default data storage virtual machine (VM) is created, an initial storage unit is created, and your data LIFs are automatically discovered. Optionally, you can enable the Domain Name System (DNS) to resolve host names, set your cluster to use the Network Time Protocol (NTS) for time synchronization, and enable encryption of data at rest.

.Before you begin

Gather the following information:

* Cluster management IP address
+
The cluster management IP address is a unique IPv4 address for the cluster management interface used by the cluster administrator to access the admin storage VM and manage the cluster. You can obtain this IP address from the administrator responsible for assigning IP addresses in your organization.
* Network subnet mask
+
During cluster setup, ONTAP recommends a set of network interfaces appropriate for your configuration.  You can adjust the recommendation if necessary.
* Network gateway IP address
* Partner node IP address
* DNS domain names
* DNS name server IP addresses
* NTP server IP addresses
* Data subnet mask

.Steps

. Power on both nodes of the HA pair.

. Show the nodes discovered on the local network: 
+
[source,cli]
----
system node show-discovered -is-in-cluster false
----

. Start the cluster setup wizard:
+  
[source,cli]
----
cluster setup
----

. Acknowledge the AutoSupport statement.

. Enter values for the node management interface port, IP address, netmask and default gateway.

. Press *Enter* to continue setup using the command line interface; then enter *create* to create a new cluster.

. Accept the system defaults or enter your own values.

. After setup on the first node is complete, log into the cluster.

. Verify that the cluster is active and the first node is healthy:  
+
[source,cli]
----
system node show-discovered
----

. Add the second node to the cluster:
+
[source,cli]
----
cluster add-node -cluster-ip <partner_node_ip_address>
----

. Optionally, synchronize the system time across the cluster
+
[cols="1h, 1"]
|===
// header column
| Synchronize without symmetric authentication
a| 
[source,cli]
----
cluster time-service ntp server create -server <server_name>
----

| Synchronize with symmetric authentication
a| 
[source,cli]
----
cluster time-service ntp server create -server <server_ip_address> -key-id <key_id>
----

// table end
|===
.. Verify that the cluster is associated with an NTP server:
+
[source,cli]
----
Cluster time-service ntp show
----

. Optionally, download and run link:https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor[ActiveIQ Config Advisor] to confirm your configuration.

.What's next?
You are ready to link:../install-setup/set-up-data-access.html[set up data access] from your SAN clients to your system.

// 2025 Jan 25, ONTAPDOC 2260
// 2024 Sept 23, ONTAPDOC 1933
