---
sidebar: sidebar
permalink: learn-more/hardware-comparison.html
keywords: compare asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30, hardware comparison, asa r2
summary: "ASA systems offer hardware support that is optimized for SAN-only solutions.  ASA r2 systems offer optimization of hardware and software."
searchtitle: "Compare ASA r2 systems to other ONTAP systems"
---
= Compare ASA r2 systems to other ONTAP systems 
:icons: font
:imagesdir: ../media/

[.lead]
ASA r2 systems offer a hardware and software solution for SAN-only environments built on all flash platforms. ASA r2 systems vary from other ONTAP systems (ASA, AFF, and FAS) in the implementation of its storage layer, supported protocols, and ONTAP personality.

On an ASA r2 system, ONTAP software is streamlined to provide support for essential SAN functionality while limiting the visibility and availability of non-SAN related features and functions. For example, System Manager running on an ASA r2 system does not display options to create home directories for NAS clients. This streamlined version of ONTAP is identified as the _ASA r2 personality_. ONTAP running on ASA systems is identified as the _ASA ONTAP personality_.  ONTAP running on AFF and FAS ONTAP systems is identified as the _unified ONTAP personality_. The differences between ONTAP personalities are referenced in the ONTAP command reference (man pages), REST API specification, and EMS messages where applicable. 

You can verify the personality of your ONTAP storage from System Manager or from the ONTAP CLI. 

* From the System Manager menu, select *Cluster > Overview*.
* From the CLI, enter: `san config show`

The personality of your ONTAP storage system cannot be changed.

The storage layer for ONTAP systems running the unified ONTAP personality uses aggregates as the base unit of storage.  An aggregate owns a specific set of the disks available in a storage system.  The aggregate allocates space on the disks it owns to volumes for LUNs and namespaces.  A unified ONTAP user can use the command line interface (CLI) to create and modify aggregates, volumes, LUNs and namespaces.  

The storage layer in ASA r2 systems uses a storage availability zone instead of aggregates. A storage availability zone is a common pool of storage that has access to all available disks in the storage system. The storage availability zone is visible to both nodes in an ASA r2 HA pair. When a storage unit (based on either a LUN or an NVMe namespace) is created, ONTAP automatically creates a volume within the selected storage virtual machine (VM) in the storage availability zone to house the storage unit.  Because of this automated and simplified approach to storage management, certain System Manager options, ONTAP commands, and REST API endpoints are not available or have limited usage on an ASA r2 system.  For example, because volume creation and management is automated for ASA r2 systems, the *Volumes* menu does not appear in System Manager and the `volume create` command is not supported.  

ASA r2 storage compares to other ONTAP storage systems in the following ways:

[cols=5*,options="header",cols="1h,2,2,2,2"]
|===
a|
a| ASA r2
a| ASA
a| AFF
a| FAS

a| *ONTAP personality*
| ASA r2
| ASA
| Unified
| Unified

a| *SAN protocol support*
| Yes
| Yes
| Yes
| Yes

a| *NAS protocol support*
| No
| No
| Yes
| Yes

a| *Storage layer support*
| Storage availability zone
| Aggregates
| Aggregates
| Aggregates

// table end
|===

The following ASA platforms are classified as ASA r2 systems:

* ASA A1K
* ASA A90
* ASA A70
* ASA A50
* ASA A30
* ASA A20
* ASA C30

.For more information

* Learn more about link:https://docs.netapp.com/us-en/ontap-systems-family/intro-family.html[ONTAP hardware systems^].
* See full configuration support and limitations for ASA and ASA r2 systems in link:https://hwu.netapp.com/[NetApp Hardware Universe^].
* Learn more about the link:https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf[NetApp ASA^].

==  Summary of ASA r2 system differences

The major differences between ASA r2 systems and FAS, AFF, and ASA systems relevant to the ONTAP command line interface (CLI) and REST API are described below.

.Default SVM creation with protocol services
New clusters automatically contain a default data SVM with the SAN protocols enabled. IP data LIFs support iSCSI and NVMe/TCP protocols and use the `default-data-blocks` service policy by default.

.Automatic volume creation
Creating a storage unit (LUN or namespace) automatically creates a volume from the storage availability zone. This results in a simplified and common namespace. Deleting a storage unit automatically deletes the associated volume.

.Changes to thin and thick provisioning
Storage units are always thinly provisioned on ASA r2 storage systems. Thick provisioning is not supported.

.Changes to data compression
Temperature-sensitive storage efficiency is not applied on ASA r2 systems. On ASA r2 systems, compression is not based on _hot_ (frequently accessed) data or _cold_ (infrequently accessed) data.  Compression begins without waiting for data to become cold. 

// 2025 June 04, ONTAPDOC-2994
// 2025 May 16, GitIssue 43
// 2025 April 10, ONTAPDOC 2892
// 2025 Feb 28, ONTAPDOC 2260
// 2024 Jan 24, ONTAPDOC 2260
// 2024 Oct 03, ONTAP GitHub Issue 1496
// 2024 Sept 23, ONTAPDOC 1933