---
sidebar: sidebar
permalink: learn-more/software-support-limitations.html
keywords: asa r2, asa a1k, asa 70, asa 90, unsupported features
summary: "While ASA r2 systems offers a wide range of support for SAN solutions, certain ONTAP software features are not supported."
---
= ONTAP software support and limitations for ASA r2 storage systems
:icons: font
:imagesdir: ../media/

[.lead]
While ASA r2 systems offers a wide range of support for SAN solutions, certain ONTAP software features are not supported.

.ASA r2 systems do not support the following:

* Default automatic iSCSI LIF failover
+
Automatic failover is enabled by default on iSCSI only LIFS.  In ASA r2 systems, the default networking LIF is shared between NVMe and SCSI hosts, and so doesn't support automatic failover. link:https://docs.netapp.com/us-en/ontap/san-admin/asa-iscsi-lif-fo-task.html#enable-automatic-iscsi-lif-failover[Create an iSCSI only LIF to enable automatic iSCSI LIF failover^].  
+
When you enable automatic LIF failover, if a storage failover occurs, the iSCSI LIF is automatically migrated from its home node or port to its HA partner node or port and then back once the failover is complete. Or, if the port for an iSCSI LIF becomes unhealthy, the LIF is automatically migrated to a healthy port in its current home node and then back to its original port once the port is healthy again.

* FabricPool
* LUN thick provisioning 
* MetroCluster 
* Object protocols
* ONTAP S3 SnapMirror and S3 APIs
* SnapMirror (Asynchronous and Synchronous) to Cloud
* SnapMirror (Asynchronous and Synchronous) to non-ASA r2 systems
* Selective LUN Map (SLM)

.ASA r2 systems support the following:

* Snaplock
* Dual-layer encryption

.For more information

* See the link:https://hwu.netapp.com/[NetApp Hardware Universe^] for more information on ASA r2 hardware support and limitations.
* link:../secure-data/ransomware-protection.html[Learn how to lock snapshots] on your ASA r2 system.
* link:../secure-data/encrypt-data-at-rest.html[Learn how to apply dual-layer encryption] to data on your ASA r2 system.

// 2024 Dec 06, GitHub issue 19
// 2024 Sept 23, ONTAPDOC 1933