---
sidebar: sidebar
permalink: learn-more/software-support-limitations.html
keywords: asa r2, asa a1k, asa a90, asa a70, asa, a50, asa a30, asa a20, asa c30, unsupported features
summary: "While ASA r2 systems offers a wide range of support for SAN solutions, certain ONTAP software features are not supported."
---
= ONTAP software support and limitations for ASA r2 storage systems
:icons: font
:imagesdir: ../media/

[.lead]
While ASA r2 systems offers a wide range of support for SAN solutions, certain ONTAP software features are not supported.

.ASA r2 systems do not support the following:

* FabricPool
* LUN thick provisioning 
* MetroCluster 
* NetApp Aggregate Encryption (NAE)
* Object protocols
* ONTAP S3 SnapMirror and S3 APIs
* SnapLock
+
SnapLock Compliance and Enterprise mode are not supported on primary clusters in SAN environments.  SnapLock for SnapVault is supported on secondary clusters.

* SnapMirror replication is supported on ASA r2 systems with the following limitations:

** SnapMirror synchronous replication is not supported.

** SnapMirror asynchronous replication is supported only between two ASA r2 systems.  SnapMirror asynchronous replication is not supported between an ASA r2 system and an ASA, AFF or FAS system or the cloud.
+
Learn more about link:../data-protection/pre-defined-protection-policies.html[SnapMirror replication policies supported on ASA r2 systems].
** SnapMirror active sync is supported only between two ASA r2 systems.
+
Learn more about link:../data-protection/snapmirror-active-sync.html[SnapMirror active sync on ASA r2 systems].

.ASA r2 systems support the following:

* Dual-layer encryption
+
ASA r2 systems support hardware encryption using self-encrypting drives (SEDs) and software encryption using NetApp Volume Encryption (NVE) technology.  link:../secure-data/encrypt-data-at-rest.html[Learn how to apply dual-layer encryption] to data on your ASA r2 system.


.For more information

* See the link:https://hwu.netapp.com/[NetApp Hardware Universe^] for more information on ASA r2 hardware support and limitations.

// 2026, Aug 07, ONTAPDOC-3890
// 2026 Jun 30, ONTAPDOC 3771
// 2025 Oct 30, ONTAPDOC 2893
// 2025 June 04, ONTAPDOC-2994
// 2025 Mar 10, GitIssue 34
// 2025 Feb 28, ONTAPDOC 2260
// 2024 Dec 06, GitHub issue 19
// 2024 Sept 23, ONTAPDOC 1933