---
sidebar: sidebar
permalink: manage-data/storage-limits.html
keywords: storage limits, cluster limits, maximum lun size, maximum, nodes per cluster, storage unit size, supported protocols, asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20,asa c30
summary: "For optimal performance, configuration and support, you should be aware of ASA r2 storage limits."
---
= ASA r2 storage limits
:icons: font
:imagesdir: ../media/

[.lead]
For optimal performance, configuration and support, you should be aware ofASA r2 storage limits.

For a complete list of the most current ASA r2 storage limits, see link:https://hwu.netapp.com/[NetApp Hardware Universe^]. 

ASA r2 systems support the following storage limits:

[cols="3", options="header"]
|===

| 
| Maximum per HA pair
| Maximum per cluster

| Consistency groups
| 256
| 256

| Enterprise applications
| 100
| 350

| Nodes
| 2
| 12

| Replication groups
| 50
| 50

| Storage availability zone size
| 2 PB
| 2 PB

| Storage units
| 10,000
| 30,000

| Storage unit size
| 128 TB
| 128 TB

| Storage units per consistency group
| 256
| 256

| Storage virtual machines
a| 
* 256 (ONTAP 9.18.1 and later)
* 32 (ONTAP 9.17.1 and earlier)

| Virtual machines
| 800
| 1200

// table end
|===

== Limits for SnapMirror asynchronous relationships

The following limits apply to storage units and consistency groups in a SnapMirror asynchronous replication relationship.  For a complete list of the most current ASA r2 storage limits, link:https://hwu.netapp.com/[NetApp Hardware Universe^].

[cols="3", options="header"]
|===

| Limit maximum
| Per HA pair   
| Per cluster

| Consistency groups
| 250
| 750

| Storage units
| 4,000
| 6,000


|===

== Limits for SnapMirror active sync relationship

The following limits apply to storage units and consistency groups in a SnapMirror active sync replication relationship. SnapMirror active sync is supported beginning with ONTAP 9.17.1 on 2-node clusters only. Beginning with ONTAP 9.18.1, SnapMirror active sync is supported on 4-node clusters.

For a complete list of the most current ASA r2 storage limits, link:https://hwu.netapp.com/[NetApp Hardware Universe^].

[cols="2", options="header"]
|===

| Limit maximum
| Per HA pair

| Consistency groups
| 50

| Storage units
| 400

|===


// 2025 Nov 06, ONTAPDOC-3264, ONTAPDOC-3358
// 2025 Oct 10, ONTAPDOC-3400
// 2025 Sept 04, ONTAPDOC-2729, ONTAPDOC-3136
// 2025 July 23, ONTAPDOC-3076
// 2025 June 04, ONTAPDOC-2994
// 2025 Feb 28, ONTAPDOC 2260, ONTAPDOC 2261
// ONTAPDOC 1922, 2024 Sept 24