---
sidebar: sidebar
permalink: manage-data/svm-post-migrate-cutover-cleanup.html
keywords: move svm, migrate svm, asa, asa r2, storage vm, storage virtual machine, manual cutover, manual cleanup, remove source svm
summary: "If a storage availability zone is running low on space, you can move storage units to another storage availability zone to balance the storage utilization across the cluster."
---
= Cutover clients and clean up source storage VM after migration to an ASA r2 system
:icons: font
:imagesdir: ../media/

[.lead]
After a storage virtual machine (VM) is migrated from an ASA cluster to an ASA r2 cluster, by default, clients are automatically cut over to the ASA r2 cluster and the storage VM on the ASA cluster is automatically removed. If you chose to disable automatic cutover and removal of the ASA storage VM during the migration, you need to perform these steps manually after the migration is complete.

== Manually cut over clients to an ASA r2 system after a storage VM migration
If you disable automatic client cutover during the migration of a storage VM from an ASA cluster to an ASA r2 cluster, after the migration is successfully complete, perform the cutover manually so the ASA r2 storage VM can serve data to clients.

.Steps

. On the ASA r2 cluster, manually execute client cutover:
+
[source,cli]
----
vserver migrate cutover -vserver <storage_VM_name>
----

. Verify that the cutover operation is complete:
+
[source,cli]
----
vserver migrate show
----

.Result

Data is being served to your clients from the storage VM on your ASA r2 cluster.  

.What’s next?
You are now ready to remove the storage VM from the source ASA cluster.

== Manually remove an ASA storage VM after migration to an ASA r2 cluster
If you disable automatic source cleanup during the migration of a storage VM from an ASA cluster to an ASA r2 cluster, after the migration is complete, remove the storage VM from the ASA cluster to free the storage space.

.Before you begin

Your clients should be serving data from the ASA r2 cluster.

.Steps

. From the ASA cluster, verify that the status of the ASA storage VM is *Ready for source cleanup*:
+
[source,cli]
----
vserver migrate show
----

. Remove the ASA storage VM:
+
[source,cli]
----
vserver migrate source-cleanup -vserver <storage_VM_name>
----

.Result
The storage VM on your ASA cluster is removed.

// 2025 Nov 06, ONTAPDOC-3345