---
sidebar: sidebar
permalink: monitor/monitor-storage.html
keywords: 
summary:
---
= Monitor cluster and storage unit utilization on the ASA r2
:icons: font
:imagesdir: ../media/

[.lead]
Monitor your storage utilization to ensure you have the storage capacity you need to serve current and future workloads.  

== Monitor cluster utilization

Regularly monitor the amount of storage consumed by your cluster to ensure that, if needed, you are prepared to expand the cluster capacity before running out of space.

.Steps

. In System Manager, select *Dashboard*.
. Under *Capacity*, view the amount of physical used space and the amount of available space on your cluster.
+
The data reduction ration represents the amount of space saved through storage efficiency.

.What's next?
If your cluster is running low on space or if it doesn't have the capacity to meet a future demand, you should plan to add new drives to your ASA r2 system to link:administer/increase-storage-capacity.html[increase your storage capacity]. 

== Monitor storage unit utilization 
Monitor the amount of storage consumed by a storage unit so that you can proactively increase the size of the storage unit based on your business needs.  

.Steps
. In System Manager, select *Storage*.
. Select the storage unit you want to monitor; then select *Overview*.
. Under *Storage*, view the following:
+
* Size of your storage unit
* Amount of used space
* Data reduction ratio
+
The data reduction ratio represents the amount of space saved through storage efficiency
* Snapshot used
+
Snapshot used represents the amount of storage used by snapshots.

.What's next?

If your storage unit is nearing capacity, you should link:../manage-data/modify-storage-units.html#edit-storage-units[edit the storage unit] to increase its size.


// ONTAPDOC 1930, 2024 Sept 24