---
sidebar: sidebar
permalink: administer/space-balancing.html
keywords: capacity, space, rebalancing, balanced, placement, balance, asa r2
summary: "You might need to rename a node to align with the naming conventions of your organization or for other administrative reasons."
---
= Learn about capacity balancing in an ASA r2 cluster
:icons: font
:imagesdir: ../media/

[.lead]
When a storage unit is created, ONTAP automatically creates a volume in a storage availability zone to house the storage unit. Capacity utilization for workloads is balanced across the storage availability zone based on your version of ONTAP.

[cols=2, options="header"]
|===
|Feature |Supported in... 

|Balanced placement |ONTAP 9.16.1 and later
|Dynamic space balancing |ONTAP 9.17.1 and later
|Copy-based workload rebalancing |ONTAP 9.16.1 only
|===


.Balanced placement
With _balanced placement_ newly created storage units are automatically placed within the best storage availability zone for optimal performance and balanced storage  utilization. Balanced placement is enabled by default in ONTAP 9.16.1 and later.

.Dynamic space balancing
With _dynamic space balancing_, ONTAP actively monitors the amount of free space in the cluster and automatically moves storage units across storage availability zones to maintain balanced space utilization.  An EMS _warning_ is automatically issued if the capacity utilization reaches 80% and an EMS _alert_ is issued if it reaches 90%.  Dynamic space balancing is enabled by default 14 days after upgrading to or installing an ONTAP 9.17.1 or later cluster. You cannot revert to ONTAP 9.16.1 after dynamic space balancing is enabled.

Dynamic space balancing operates in either _normal mode_ or _low space mode_ based on the overall average of free space in all nodes in the cluster (global average).

* *Normal mode*
+
In normal mode, ONTAP checks every three minutes to determine if dynamic space balancing is needed. Dynamic space balancing is triggered in normal mode when the following conditions are true:  
+
** The global average for free space is 10% or more.
** At least one node in the cluster has more free space that the global average.
** At least one node in the cluster has 20% less free space than the global average.



* *Low space mode*
+
In low space mode, ONTAP checks every minute to determine if dynamic space balancing is needed. Dynamic space balancing operates in low space mode when the following conditions are true:
+
** The global average for free space is less than 10%.
** At least one node in the cluster has more free space that the global average.        
** At least one node in the cluster has less free space than the global average.

.Copy-based workload rebalancing

With _copy-based workload rebalancing_, if an imbalance in storage utilization occurs across the storage availability zones, ONTAP automatically copies the storage unit creating the imbalance to a storage availability zone with greater free space. If there is not enough free space in the destination storage availability zone, ONTAP does not perform any balancing action. Copy-based workload rebalancing is enabled by default in ONTAP 9.16.1 only. In ONTAP 9.17.1 and later, it is replaced with dynamic space balancingd.

// 2025 Dec 12, ONTAPDOC 3522