---
sidebar: sidebar
permalink: administer/upgrade-ontap.html
keywords: update, firmware, system files, automatic updates, automated updates, asa r2, disable, 
summary: "ONTAP software upgrades for ASA r2 systems follow the same process as upgrades for other ONTAP systems. When you upgrade your ONTAP software on your ASA r2 system, you can take advantage of new and enhanced ONTAP features."
---
= Upgrade ONTAP on ASA r2 storage systems
:icons: font
:imagesdir: ../media/

[.lead]
When you upgrade your ONTAP software on your ASA r2 system, you can take advantage of new and enhanced ONTAP features that can help you reduce costs, accelerate critical workloads, improve security, and expand the scope of data protection available to your organization.

ONTAP software upgrades for ASA r2 systems follow the same process as upgrades for other ONTAP systems.  It is recommended that you get stared by link:https://docs.netapp.com/us-en/ontap/upgrade/create-upgrade-plan.html[preparing for your upgrade with Upgrade Advisor in Active IQ Digital Advisor or Upgrade Health Checker^].

After you prepare for your upgrade, it is recommended that you perform upgrades using link:https://docs.netapp.com/us-en/ontap/upgrade/task_upgrade_andu_sm.html[automated non-disruptive upgrade (ANDU) from System Manager^]. ANDU takes advantage of ONTAP’s high-availability (HA) failover technology to ensure that clusters continue to serve data without interruption during the upgrade.

Learn more about link:https://docs.netapp.com/us-en/ontap/upgrade/index.html[ONTAP software upgrades^]. 

== Execute automated pre-upgrade checks before a planned upgrade

You don't have to be in the process of upgrading your ONTAP software to execute the ONTAP automated upgrade pre-checks. Executing the pre-upgrade checks independently of the ONTAP automated upgrade process allows you to see which checks are performed against your cluster and gives you a list of any errors or warnings that should be corrected before you begin the actual upgrade. Beginning with ONTAP 9.19.1, errors and warning are displayed separately to help you easily identify issues that must be resolved before you upgrade.  

Learn how to link:https://docs.netapp.com/us-en/ontap/upgrade/automated-pre-checks.html[run ONTAP automated pre-upgrade checks^].


// 2026, May 07, ONTAPDOC 3600
// 2025, Jan 24, ONTAPDOC 2621