---
sidebar: sidebar
permalink: videos/video_transcript_configure_san_storage.html
keywords: frontmatter, front matter
summary: View short videos that demonstrate how to use ONTAP System Manager to quickly and easily perform common task on your ASA r2 storage systems.
---
= Configure SAN protocols on your ASA r2 system
:icons: font
:imagesdir: ../media/

[.lead]

The following transcript is provided for the video `Provision SAN storage on your ASA r2 storage system`.

link:videos-common-tasks.html#video_transcript_return_provision_san_storage[Return to page]

You can use ONTAP System Manager to quickly and easily provision storage units for hosts on your ASA r2 storage system. 

For this example, we'll create six new storage units for a VMware host.  From the System Manager menu, select *Storage*, then select *Add*.  

Enter a name for the storage units, the number of units, and the capacity for each unit; then select your host operating system.  

If you create more than one unit, by default, each unit is created with the same capacity. 

Select *More Options* to enter your host information. For this example, we’ll select the SCSI protocol and add a new iSCSI host.

Enter the host name, then add the host initiators and a description.  

Select *schedule snapshots* protect your storage units with regular snapshots.  
 
Select remote protection to *replicate your units to a remote location*.  
 
Select a storage vM and replication policy; the select *Add*. 
 
The storage units must be in a consistency group for replication.  Enter a consistency group name and Select *Create*.  
  
You have quickly and easily provisioned 6 storage units for VMware hosts with local and remote data protection.

// 2024 Sept 23, ONTAPDOC 2393