---
sidebar: sidebar
permalink: get-started/learn-about.html
keywords: asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30, learn more, learn about, get started
summary: "ASA r2 systems (ASA A1K, A90, A70, A50, A30, A20, C30) offer a unified hardware and software solution for a simplified experience for SAN-only customers."
searchtitle: "Learn about ASA A1K, A90, A70, A50, A30 A20 and C30 systems"
---
= Learn about ASA r2 storage systems
:icons: font
:imagesdir: ../media/

[.lead]

The NetApp ASA r2 systems deliver a unified hardware and software solution that creates a simplified experience specific to the needs of SAN-only customers.

The following are classified as ASA r2 systems:

* ASA A1K
* ASA A90
* ASA A70
* ASA A50
* ASA A30
* ASA A20
* ASA C30

ASA r2 systems support all SAN protocols (iSCSI, FC, NVMe/FC, NVMe/TCP).  The iSCSI, FC, NVMe/FC and NVMe/TCP protocols support symmetric active-active architecture for multipathing so that all paths between the hosts and storage are active/optimized. The iSCSI and NVMe/TCP protocols support direct attach between the hosts and storage. For Fibre Channel and NVMe/FC protocols direct attach is not supported.

On an ASA r2 system, ONTAP software and System Manager are streamlined to provide support for essential SAN functionality while removing features and functions not supported in SAN environments.  

ASA r2 systems introduce the use of storage units with consistency groups:

* A _storage unit_ makes storage space available to your SAN hosts for data operations. A storage unit refers to a LUN for SCSI hosts or an NVMe namespace for NVMe hosts. 
* _A consistency group_ is a collection of storage units that are managed as a single unit.  

ASA r2 systems use storage units with consistency groups to simplify storage management and data protection.  For example, suppose you have a database consisting of 10 storage units in a consistency group, and you need to back up the entire database. Instead of backing up each storage unit individually, you can protect the entire database by backing up the consistency group.

To help secure your data against malicious attacks such as theft or ransomware, ASA r2 systems support an on-board key manager, dual-layer encryption, multi-factor authentication and multi-admin verification.  Tamper-proof snapshots are also supported on secondary ASA r2 systems.

ASA r2 systems do not support cluster mixing with ASA, AFF, or FAS systems.

.For more information

* Learn more about ASA r2 systems support and limitations in the link:https://hwu.netapp.com/[NetApp Hardware Universe^].
* Learn more about link:../learn-more/hardware-comparison.html[the ASA r2 systems in comparison to the ASA systems].
* Learn more about the link:https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf[NetApp ASA^].


// 2025 Oct 02, GitIssue 75
// 2025 Aug, 19, ONTAPDOC-2494
// 2025 June 20, ONTAPDOC-3087
// 2025 June 04, ONTAPDOC-2994
// 2025 Feb 28, ONTAPDOC 2260
// 2025 Jan 31, ONTAPPM-103027
// 2025 Jan 25, ONTAPDOC 2260, ONTAPDOC 2261
// 2024 Dec 06, GitHub Issue 18
// 2024 Nov 07, ONTAPDOC 2237
// 2024 Sept 23, ONTAPDOC 1921