---
sidebar: sidebar
permalink: data-protection/manage-consistency-groups.html
keywords: consistency groups, snapshots, data protection, protect data, add, remove, delete, storage units, lun, namespace, increase capacity
summary: Use consistency groups to perform various actions to multiple storage units at the same time instead of performing actions individually on each unit.  
---
= Manage ONTAP consistency groups on ASA r2 storage systems
:icons: font
:imagesdir: ../media/

[.lead]
A consistency group is a collection of storage units that are managed as a single unit. Use consistency groups for simplified storage management. 

For example, suppose you have a database consisting of 10 storage units in a consistency group, and you need to back up the entire database.  Instead of backing up each storage unit, you can back up the entire database by simply adding snapshot data protection to the consistency group. Backing up the storage units as a consistency group instead of individually also provides a consistent backup of all the units, while backing up units individually could potentially create inconsistencies.

== Consistency groups in replication relationships

Beginning with ONTAP 9.17.1, you can make the following geometry changes to consistency groups in an asynchronous replication relationship or in a SnapMirror active sync relationship without breaking or deleting the relationship.  When a geometry change occurs on the primary consistency group, the change is replicated to the secondary consistency group.

* link:manage-consistency-groups-add-remove-storage-units.html[Modify the size of a storage unit] by adding or removing storage units.
* link:manage-hierarchical-consistency-groups.html#promote-an-existing-consistency-group-into-a-parent-consistency-group[Promote a single consistency group] to a parent consistency group.
* link:manage-hierarchical-consistency-groups.html#demote-a-parent-consistency-group-to-a-single-consistency-group[Demote a parent consistency group] to a single consistency group.
* link:manage-hierarchical-consistency-groups.html#detach-a-child-consistency-group-from-a-parent-consistency-group[Detach a child consistency group] from a parent consistency group.
* link:manage-hierarchical-consistency-groups.html#create-a-child-consistency-group[Create a child consistency group] using an existing consistency group.

In ONTAP 9.16.1, you must link:snapmirror-active-sync-break-relationship.html[break the asynchronous replication relationship] and link:snapmirror-active-sync-delete-relationship.html[delete the SnapMirror active sync relationship] before making geometry changes to the consistency group.

// 2025 Sep 04, ONTAPDOC-2732
// 2024 Sept 24, ONTAPDOC 1927