---
sidebar: sidebar
permalink: data-protection/manage-consistency-groups.html
keywords: consistency groups, snapshots, data protection, protect data, add, remove, delete, storage units, lun, namespace, increase capacity
summary: Use consistency groups to perform various actions to multiple storage units at the same time instead of performing actions individually on each unit.  
---
= Manage ONTAP consistency groups on ASA r2 storage systems
:icons: font
:imagesdir: ../media/

[.lead]
A consistency group is a collection of storage units that are managed as a single unit. Use consistency groups for simplified storage management. 

For example, suppose you have a database consisting of 10 storage units in a consistency group, and you need to back up the entire database.  Instead of backing up each storage unit, you can back up the entire database by simply adding snapshot data protection to the consistency group. Backing up the storage units as a consistency group instead of individually also provides a consistent backup of all the units, while backing up units individually could potentially create inconsistencies.

== Consistency groups in SnapMirror active sync relationships

Beginning in ONTAP 9.17.1, you can make the following geometry changes to consistency groups in a SnapMirror active sync relationship without breaking the relationship.  When geometry a change occurs on the primary consistency group, the change is replicated to the secondary consistency group.

* Modify the size of a storage unit by adding or removing storage units.
* Promote a single consistency group to a parent consistency group.
* Demote a parent consistency group to a single consistency group.
* Detach a child consistency group from a parent consistency group.
* Move storage units between consistency groups.

In ONTAP 9.16.1, you must break the SnapMirror active sync relationship before making geometry changes to the consistency group.


// 2024 Sept 24, ONTAPDOC 1927