---
sidebar: sidebar
permalink: data-protection/protect-data.html
keywords: data protection, protect data, asa r2, snapshot, replication, snapshot replication, data replication, disaster recovery, backup
summary: Use Snapshot and Snapshot replication to create local and remote copies of your data for backup, data migration and disaster recovery.
---
= Data protection with the ASA r2
:icons: font
:imagesdir: ../media/

[.lead]
Use snapshots and snapshot replication to protect data on your ASA r2. A snapshot is a local read-only copy of your data that you can use to restore storage units to specific points in time.  Snapshot replication can be used for data migration or disaster recovery by creating copies of your data on a cluster in a geographically remote site.

After a snapshot is created, the active file system and the snapshot point to the same disk blocks; therefore, the snapshot doesn't use extra disk space. Over time, the image consumes minimal storage space and incurs negligible performance overhead because it records only changes to files since the last snapshot copy was made.

Snapshots can be created on demand and can be created automatically in regular intervals based on a snapshot policy. The Snapshot policy specifies when to create the snapshots, how many copies to retain, how to name them, and how to label them for replication. For example, a system might create one snapshot every day at 12:10 a.m., retain the two most recent copies, name them “daily” (appended with a timestamp), and label them “daily” for replication.

// ONTAPDOC 1927, 2024 Sept 24