---
sidebar: sidebar
permalink: data-protection/snapmirror-active-sync-remove-configuration.html
keywords: asa r2, data protection, business continuity, remove, delete, snapmirror active sync, disaster recovery
summary: "Use SnapMirror active sync, to protect host applications that require a zero recovery point objective (RPO) and a zero recovery time objective (RTO) from outages due to an unexpected disruption or site disaster."
---
= Remove a SnapMirror active sync configuration
:icons: font
:imagesdir: ../media/

[.lead]
If you no longer require near zero RPO and RTO for your business-critical applications, you can remove the SnapMirror active sync configuration from your ASA r2 system.

Deleting the relationship is not allowed in the failed-over state when the relationship is not reversed.

.Before you begin

* All storage units in the destination cluster must be unmapped.
+
After the LUNs are unmapped and the host is rescanned, the SCSI target notifies the hosts that the LUN inventory has changed. The existing LUNs on the zero RTO secondary volumes change to reflect a new identity after the zero RTO relationship is deleted. Hosts discover the secondary volume LUNs as new LUNs that have no relationship to the source volume LUNs.
