---
sidebar: sidebar
permalink: /data-protection/snap-mirror-active-sync-prepare.html
keywords: asa r2, data protection, business continuity, snapmirror active sync, protocol support, object limits, NVMe protocol limitations, prerequisites, interoperability, limits
summary: "To prepare to configure SnapMirror active sync on your ASA r2 system you should review the configuration prerequisites, confirm support for your hosts operating systems, and be aware of object limits that might impact specific configuration."
---
= Prepare to configure SnapMirror active sync on ASA r2 systems
:icons: font
:imagesdir: ../media/

[.lead]

To prepare to configure SnapMirror active sync on your ASA r2 system you should review the configuration prerequisites, confirm support for your hosts operating systems, and be aware of object limits that might impact specific configuration.

.Steps

. Review SnapMirror active sync link:https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/prerequisites-reference.html[prerequisites^]. 
. link:https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/interoperability-reference.html[Confirm that your host operating systems are supported^] for SnapMirror active sync. 
. Review the link:https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/limits-reference.html[object limits] that might impact your configuration.
. Veirfy host protocol support for SnapMirror active sync on your ASA r2 system.
+
Support for SnapMirror active sync on ASA r2 systems varies based upon ONTAP version and host protocol.
+
[cols="2,2" options="header"]
|===
| Beginning with ONTAP... | SnapMirror active sync supports...

| 9.16.0
a|
* iSCSI
* FF

| 9.17.1
a|
* iSCSI
* FC    
* NVMe/FC
* NVMe/TCP
|===

== NVMe protocol limitations with SnapMirror active sync on ASA r2 systems

Before you configure SnapMirror active sync on as ASA r2 system with NVMe hosts, you should be aware of certain NVMe protocol limitations.  For ASA r2 systems, the NVMe/FC and NVMe/TCP protocols are supported with SnapMirror active sync only on 2-node clusters and on ESXi hosts only.  Clusters larger than 2 nodes and other hosts types are not supported. 

All the NVMe storage units in the NVMe subsystem must be members of the same consistency group and must all be part of the same SnapMirror active sync relationship. If the storage units in the NVMe subsystem are not all members of the same consistency group, you cannot link:link: data-protection/manage-consistency-groups.html#add-storage-units-to-a-consistency-group[expand the consistency group]. 

SnapMirror active sync with NVMe does not support the following:

* Removing a storage unit from a consistency group
* Consistency group geometry change
* NS copy offload

.What’s next?

After you have completed the preparation necessary to enable SnapMirror active sync, you should link:snap-mirror-active-sync-confirm-cluster-configuration.html[confirm your cluster configuration].
// 2025 Jul 24, ONTAPDOC-2707