---
sidebar: sidebar
permalink: data-protection/snapmirror-active-sync-prepare.html
keywords: asa r2, data protection, business continuity, snapmirror active sync, protocol support, object limits, NVMe protocol limitations, prerequisites, interoperability, limits
summary: "To prepare to configure SnapMirror active sync on your ASA r2 system you should review the configuration prerequisites, confirm support for your hosts operating systems, and be aware of object limits that might impact specific configuration."
---
= Prepare to configure SnapMirror active sync on ASA r2 systems
:icons: font
:imagesdir: ../media/

[.lead]
To prepare to configure SnapMirror active sync on your ASA r2 system you should review the configuration prerequisites, confirm support for your hosts operating systems, and be aware of object limits that might impact specific configuration.

.Steps

. Review the SnapMirror active sync link:https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/prerequisites-reference.html[prerequisites^]. 
. link:https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/interoperability-reference.html[Confirm that your host operating systems are supported^] for SnapMirror active sync. 
. Review the link:https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/limits-reference.html[object limits] that might impact your configuration.
. Verify host protocol support for SnapMirror active sync on your ASA r2 system.
+
Support for SnapMirror active sync on ASA r2 systems varies based upon ONTAP version and host protocol.
+
[cols="2,2" options="header"]
|===
| Beginning with ONTAP... | SnapMirror active sync supports...

| 9.17.1
a|
* iSCSI
* FC    
* NVMe/FC
* NVMe/TCP

| 9.16.0
a|
* iSCSI
* FC
|===

== NVMe protocol limitations with SnapMirror active sync on ASA r2 systems

Before you configure SnapMirror active sync on an ASA r2 system with NVMe hosts, you should be aware of certain NVMe protocol limitations.  

All NVMe storage units in the NVMe subsystem must be members of the same consistency group and must all be part of the same SnapMirror active sync relationship. 

The NVMe/FC and NVMe/TCP protocols are supported with SnapMirror active sync as follows:

* Only on 2-node clusters
* Only on ESXi hosts
* Only with symmetric active/active configurations
+
Asymmetric active/active configurations are not supported with NVMe hosts. 

SnapMirror active sync with NVMe does not support the following:

* Subsystems mapped to more than one consistency group
+
A consistency group can be mapped with multiple subsystems, but each subsystem can be mapped to only one consistency group.
* Expansion of consistency groups in a SnapMirror active sync relationship
* Mapping NVMe storage units that are not in a SnapMirror active sync relationship to replicated subsystems
* Removing a storage unit from a consistency group
* Consistency group geometry change
* link:https://docs.netapp.com/us-en/ontap/san-admin/microsoft-offloaded-data-transfer-odx-concept.html[Microsoft Offloaded Data Transfer (ODX)]

.What’s next?

After you have completed the preparation necessary to enable SnapMirror active sync, you should link:snapmirror-active-sync-confirm-cluster-configuration.html[confirm your cluster configuration].
// 2025 Jul 24, ONTAPDOC-2707