---
sidebar: sidebar
permalink: release-notes/changes-to-limits-defaults.html
keywords: release notes, changes, updates, defaults, limits, asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30
summary:  Learn about the changes to limits and defaults affecting ASA r2 systems. 
---
= Changes to ONTAP limits and defaults affecting ASA r2 systems
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Learn about the changes to limits and defaults affecting ASA r2 systems. NetApp strives to help its customers understand the most important default and limit changes in each ONTAP release.

== Changes to ONTAP limits

[cols="2,4,4" options="header"]
|===

| Feature
| Limit change
| Changed in release...

| SVMs per cluster
| The maximum number of storage virtual machines (SVMs) per HA pair is increased from 32 to 256.
| ONTAP 9.18.1

| Nodes per cluster
a| The maximum number of nodes per cluster is increased from 2 to 12.
[NOTE] 
If you are running ONTAP 9.16.1 with more than 2 nodes in a cluster, you cannot revert to ONTAP 9.16.0.

| ONTAP 9.16.1

| Storage units
| The maximum number of storage units is increased from 2500 per HA pair to 10,000 per HA pair.
| ONTAP 9.16.1

|===

// 2025 Nov 06, ONTAPDOC-3266
// 2025 June 04, ONTAPDOC-2994
// 2025 Feb 28, ONTAPDOC 2260
// 2025 Jan 24, ONTAPDOC 2410, 2261
// 2024 Nov 07, ONTAPDOC 2237